# STUDENT DROPOUT PREDICTION

In [125]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [126]:
data=pd.read_csv('student_dropout_dataset.csv')

In [127]:
data.head()

,age,gender,admission_grade,attendance_percentage,study_hours_per_day,scholarship,tuition_fees_paid,parents_education,family_income,exam_score,dropout_status
0,24,Male,100,93,2,Yes,Yes,Diploma,15152,45,1
1,18,Male,90,46,4,Yes,No,Bachelor,29727,84,1
2,22,Male,148,97,3,No,Yes,HighSchool,76278,77,0
3,21,Male,142,69,1,Yes,No,Master,88695,59,1
4,23,Male,120,73,4,Yes,No,Diploma,51806,45,1

In [128]:
data.tail()

,age,gender,admission_grade,attendance_percentage,study_hours_per_day,scholarship,tuition_fees_paid,parents_education,family_income,exam_score,dropout_status
995,22,Female,141,68,5,No,Yes,Bachelor,64325,84,0
996,19,Male,146,93,3,No,Yes,Master,88315,70,0
997,24,Female,112,42,2,Yes,Yes,HighSchool,23202,48,1
998,19,Male,105,92,4,Yes,Yes,Master,78310,63,0
999,19,Male,147,57,2,No,Yes,HighSchool,83958,75,1

In [129]:
data.shape

(1000, 11)

In [130]:
data.columns

Index(['age', 'gender', 'admission_grade', 'attendance_percentage',
       'study_hours_per_day', 'scholarship', 'tuition_fees_paid',
       'parents_education', 'family_income', 'exam_score', 'dropout_status'],
      dtype='object')

In [131]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    1000 non-null   int64
 1   gender                 1000 non-null   object
 2   admission_grade        1000 non-null   int64
 3   attendance_percentage  1000 non-null   int64
 4   study_hours_per_day    1000 non-null   int64
 5   scholarship            1000 non-null   object
 6   tuition_fees_paid      1000 non-null   object
 7   parents_education      1000 non-null   object
 8   family_income          1000 non-null   int64
 9   exam_score             1000 non-null   int64
 10  dropout_status         1000 non-null   int64
dtypes: int64(7), object(4)
memory usage: 86.1+ KB

In [132]:
data.describe()

,age,admission_grade,attendance_percentage,study_hours_per_day,family_income,exam_score,dropout_status
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,20.943000,119.974000,69.073000,3.093000,53659.312000,69.828000,0.78400
std,1.986378,17.356975,17.493247,1.379222,26068.308623,17.468072,0.41172
min,18.000000,90.000000,40.000000,1.000000,10097.000000,40.000000,0.00000
25%,19.000000,106.000000,54.000000,2.000000,30632.250000,55.000000,1.00000
50%,21.000000,120.000000,68.000000,3.000000,53178.000000,69.000000,1.00000
75%,23.000000,135.000000,85.000000,4.000000,77130.750000,86.000000,1.00000
max,24.000000,149.000000,99.000000,5.000000,99922.000000,99.000000,1.00000

In [133]:
data.isnull().sum()

age                      0
gender                   0
admission_grade          0
attendance_percentage    0
study_hours_per_day      0
scholarship              0
tuition_fees_paid        0
parents_education        0
family_income            0
exam_score               0
dropout_status           0
dtype: int64

In [134]:
label_cols = ['gender', 'scholarship', 'tuition_fees_paid', 'parents_education']

encoders = {}
for col in label_cols:
    encoders[col] = LabelEncoder()
    data[col] = encoders[col].fit_transform(data[col])

In [135]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    1000 non-null   int64
 1   gender                 1000 non-null   int64
 2   admission_grade        1000 non-null   int64
 3   attendance_percentage  1000 non-null   int64
 4   study_hours_per_day    1000 non-null   int64
 5   scholarship            1000 non-null   int64
 6   tuition_fees_paid      1000 non-null   int64
 7   parents_education      1000 non-null   int64
 8   family_income          1000 non-null   int64
 9   exam_score             1000 non-null   int64
 10  dropout_status         1000 non-null   int64
dtypes: int64(11)
memory usage: 86.1 KB

In [136]:
x=data.drop(columns=['dropout_status'])
y=data['dropout_status']

In [137]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [138]:
model = RandomForestClassifier(n_estimators=200,random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [139]:
print(x_train.dtypes)
print(y_train.dtypes)

age                      int64
gender                   int64
admission_grade          int64
attendance_percentage    int64
study_hours_per_day      int64
scholarship              int64
tuition_fees_paid        int64
parents_education        int64
family_income            int64
exam_score               int64
dtype: object
int64

In [140]:
y_pred = model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.995

Confusion Matrix:
[[ 47   1]
 [  0 152]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        48
           1       0.99      1.00      1.00       152

    accuracy                           0.99       200
   macro avg       1.00      0.99      0.99       200
weighted avg       1.00      0.99      0.99       200

In [141]:
# Encode categorical values
gender = encoders['gender'].transform(['Male'])[0]
scholarship = encoders['scholarship'].transform(['Yes'])[0]
tuition = encoders['tuition_fees_paid'].transform(['Yes'])[0]
parents = encoders['parents_education'].transform(['Bachelor'])[0]

# Create input features
input_features = np.array([[ 
    20, 
    gender, 
    85.0, 
    90.0, 
    5.0, 
    scholarship, 
    tuition, 
    parents, 
    50000.0, 
    78.0
]])

# Prediction
prediction = model.predict(input_features)[0]

if prediction == 1:
    result = "The student is predicted to drop out."
else:
    result = "The student is predicted not to drop out."

print(result)

prob= model.predict_proba(input_features)[0][1]

print("Dropout Probability:", round(prob*100,2),"%")

The student is predicted not to drop out.
Dropout Probability: 6.0 %

c:\Users\mouni\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\mouni\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [142]:
import pickle

# Save the model
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

# Save the encoders
with open('encoders.pkl', 'wb') as f:
    pickle.dump(encoders, f)

print("Model and encoders saved successfully.")

Model and encoders saved successfully.